version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - my_data:/var/www/storage/cache
    networks:
      - corelab
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=corelab_challenge
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - corelab

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100M
    networks:
      - corelab

  web:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api
    networks:
      - corelab

networks:
  corelab:

volumes:
  my_data:
  mysql_data: