version: '3.8'

services:
  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-corelab
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app_network

  # API Laravel (Backend)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    command: >
      sh -c "sleep 10 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
